package Problem2;

/**
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2
{
    public static void main(String[] args)
    {
        int result=0;
        int left = 1, right=2;

        while (right < 4000000){

            int temp = left+right;
            left = right;
            right = temp;

            if(left % 2 == 0)
                result += left;

            if(right %2 == 0)
                result += right;
        }

        System.out.println(result);

    }
}
