package com.jameselsey.jameselsey.demos.projecteuler.problem2;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * <p/>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p/>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * <p/>
 * ANSWER:4613732
 */
public class Problem2
{
    public static void main(String[] args)
    {
        long start = System.currentTimeMillis();
        int result = execute(4000000);
        long end = System.currentTimeMillis();
        long duration = end - start;

        System.out.format("Answer: [%d], took %d milliseconds to solve", result, duration);
    }


    public static int execute(int upperLimit)
    {
        // since we start with 1 & 2, we can assume result always starts from 2, as it's even
        int result = 2;
        int left = 1;
        int right = 2;

        while (left + right < upperLimit)
        {
            int temp = left + right;
            left = right;
            right = temp;
            if (right % 2 == 0)
            {
                result += right;
            }
        }

        return result;
    }
}
